// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1VRjaoutswhjjxSRKrHArPoiFHuf7bvI',
    appId: '1:378189380951:web:a6dd143a4de2b53872d212',
    messagingSenderId: '378189380951',
    projectId: 'farmer-ai-12c6c',
    authDomain: 'farmer-ai-12c6c.firebaseapp.com',
    storageBucket: 'farmer-ai-12c6c.firebasestorage.app',
    measurementId: 'G-WHRF6790SG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfFHDTKYyr5_y9mpsCnzl51ap0qwg94y0',
    appId: '1:378189380951:android:3f3cdc47e7d2983572d212',
    messagingSenderId: '378189380951',
    projectId: 'farmer-ai-12c6c',
    storageBucket: 'farmer-ai-12c6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjUfIVgX7O7OsG92AfyhgNBRW86PpuLp0',
    appId: '1:378189380951:ios:21463d391d39196b72d212',
    messagingSenderId: '378189380951',
    projectId: 'farmer-ai-12c6c',
    storageBucket: 'farmer-ai-12c6c.firebasestorage.app',
    iosBundleId: 'com.example.farmerAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjUfIVgX7O7OsG92AfyhgNBRW86PpuLp0',
    appId: '1:378189380951:ios:21463d391d39196b72d212',
    messagingSenderId: '378189380951',
    projectId: 'farmer-ai-12c6c',
    storageBucket: 'farmer-ai-12c6c.firebasestorage.app',
    iosBundleId: 'com.example.farmerAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1VRjaoutswhjjxSRKrHArPoiFHuf7bvI',
    appId: '1:378189380951:web:d0d14473e86ad95472d212',
    messagingSenderId: '378189380951',
    projectId: 'farmer-ai-12c6c',
    authDomain: 'farmer-ai-12c6c.firebaseapp.com',
    storageBucket: 'farmer-ai-12c6c.firebasestorage.app',
    measurementId: 'G-XSJBDN0XLD',
  );
}
